config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :price_per_night, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]
  before_action :set_new_flat, only: [:new, :index]

  # GET /flats or /flats.json
  def index
    @flats = Flat.order(created_at: :desc)
  end

  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)
    @flats = Flat.all

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flats_path, notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_new_flat
      @flat = Flat.new
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :description, :address, :price_per_night)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div class="card">
  <img src="https://source.unsplash.com/1600x900/?#{flat.name}" class="card-img-top" alt="<%= flat.name %>">
  <div class="card-body">
    <h5 class="card-title"><%= flat.name %></h5>
    <p class="card-text"><%= flat.description %></p>
    <%= link_to 'View', flat, class: 'btn btn-info btn-block'  %>
  </div>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :price_per_night %>
  <%= f.button :submit, class: 'btn btn-info btn-block' %>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<div class="container my-3">
  <h1>All our flats (<%= @flats.count %>)</h1>

  <div class="row">
    <div class="col-8">
      <div class="cards">
        <%= render @flats %>
      </div>
    </div>
    <div class="col-4">
      <%= render 'form', flat: @flat %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add flat</h1>
  <%= render 'form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://source.unsplash.com/1600x900/?#{@flat.name}');">
  <div class="container">
  </div>
</div>

<div class="container my-3">
  <div class="row">
    <div class="col-8">
      <div class="my-3">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>
      <div>
        <h2>A bit more about this flat...</h2>
        <p><%= @flat.description %></p>
      </div>
    </div>
    <div class="col-4">
      <h2>Sidebar</h2>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'Simple Airbnb', root_path, class: 'navbar-brand' %>
  <%= link_to 'Add flat', new_flat_path, class: 'btn btn-outline-info my-2 my-sm-0' %>
</nav>